apiVersion: v1
kind: ConfigMap
metadata:
  name: dawning-config
  namespace: dawning
  labels:
    app.kubernetes.io/name: dawning
data:
  # MySQL
  MYSQL_DATABASE: "dawning_identity"
  MYSQL_USER: "dawning"
  
  # Kafka
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_NUM_PARTITIONS: "3"
  
  # Zookeeper
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  
  # Application
  ASPNETCORE_ENVIRONMENT: "Production"
  TZ: "Asia/Shanghai"
