apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dawning

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  # Infrastructure
  - mysql
  - redis
  - zookeeper
  - kafka
  # Applications
  - identity-api
  - gateway-api
  - admin-frontend
  # Networking
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: dawning-gateway
  app.kubernetes.io/managed-by: kustomize
