{{- if .Values.certificates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawning.fullname" . }}-certificates
  labels:
    {{- include "dawning.labels" . | nindent 4 }}
type: Opaque
data:
  signing.pfx: {{ .Files.Get "files/certificates/signing.pfx" | b64enc }}
  encryption.pfx: {{ .Files.Get "files/certificates/encryption.pfx" | b64enc }}
{{- end }}
