{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawning.fullname" . }}-secrets
  labels:
    {{- include "dawning.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.external.enabled }}
  DATABASE_PASSWORD: {{ .Values.database.external.password | b64enc | quote }}
  {{- else if .Values.mysql.enabled }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.cache.external.enabled }}
  REDIS_PASSWORD: {{ .Values.cache.external.password | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ default (include "dawning.randomSecret" .) .Values.secrets.jwtSecret | b64enc | quote }}
  OPENIDDICT_KEY: {{ default (include "dawning.randomSecret" .) .Values.secrets.openIddictKey | b64enc | quote }}
{{- end }}
