{{- if .Values.gatewayApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dawning.fullname" . }}-gateway-api
  labels:
    {{- include "dawning.gatewayApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewayApi.service.type }}
  ports:
    - port: {{ .Values.gatewayApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dawning.gatewayApi.selectorLabels" . | nindent 4 }}
{{- end }}
