apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: dawning
  labels:
    app: identity-api
    app.kubernetes.io/name: identity-api
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      name: http
  selector:
    app: identity-api
