{{- if and .Values.identityApi.enabled .Values.identityApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dawning.fullname" . }}-identity-api
  labels:
    {{- include "dawning.identityApi.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dawning.fullname" . }}-identity-api
  minReplicas: {{ .Values.identityApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.identityApi.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.identityApi.autoscaling.targetCPUUtilization }}
{{- end }}
