{{- if .Values.identityApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dawning.fullname" . }}-identity-api
  labels:
    {{- include "dawning.identityApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.identityApi.service.type }}
  ports:
    - port: {{ .Values.identityApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dawning.identityApi.selectorLabels" . | nindent 4 }}
{{- end }}
