apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dawning

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

# Moderate replicas for staging
replicas:
  - name: identity-api
    count: 2
  - name: gateway-api
    count: 2
  - name: admin-frontend
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: dawning-config
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: "Staging"
