apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dawning

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

# Moderate replicas for staging
replicas:
  - name: identity-api
    count: 2
  - name: gateway-api
    count: 2
  - name: admin-frontend
    count: 2

configMapGenerator:
  - name: dawning-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Staging
