{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawning.fullname" . }}-secrets
  labels:
    {{- include "dawning.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.external.enabled }}
  database-password: {{ .Values.database.external.password | b64enc | quote }}
  {{- else if .Values.mysql.enabled }}
  database-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.cache.external.enabled }}
  redis-password: {{ .Values.cache.external.password | b64enc | quote }}
  {{- end }}
  jwt-secret: {{ default (include "dawning.randomSecret" .) .Values.secrets.jwtSecret | b64enc | quote }}
  openiddict-key: {{ default (include "dawning.randomSecret" .) .Values.secrets.openIddictKey | b64enc | quote }}
{{- end }}
